[build]
  publish="dist"
  command="gridsome build"
  functions = "functions"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
package = "netlify-plugin-image-optim"


[[plugins]]
  package = "netlify-plugin-gridsome-cache"
